apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-from-vs
spec:
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: test-backup
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
